### ISSUE TITLE
Karakurt

### ISSUE THREAD

**Issue by ocbrollingpaper** [fastfire/deepdarkCTI#196]
Heyo, Karakurt has been operating on DW, I am trying to find link, if anyone has one do they mind opening PR to this repo or sending it here?

![BF714FB7-BA17-4437-82DB-C690AD63D072](https://user-images.githubusercontent.com/45208722/149218098-e7b994f5-64b2-4be3-a61c-47ce6c66e59d.jpg)

**Comment by soufianetahiri** [comment]
Looking for it too.
Commenting to get notified.

**Comment by ocbrollingpaper** [comment]
Found it!

**Comment by soufianetahiri** [comment]
So? 😁..

**Comment by ocbrollingpaper** [comment]
Guess they just took it down, was live today. We started scraping it this morning........

**Comment by soufianetahiri** [comment]
Thanks for sharing.
