### ISSUE TITLE
New Leaks website

### ISSUE THREAD

**Issue by nuke86** [fastfire/deepdarkCTI#32]
Hi,
I have been following the project for a few days, I found in the Twitter feed a new recent site linked to Karma ransomware: 3nvzqyo6l4wkrzumzu5aod7zbosq4ipgf7ifgj3hsvbcr5vcasordvqd.onion

**Comment by fastfire** [comment]
Thank you @nuke86 !

**Comment by fastfire** [comment]
Merged by @nrrpinto
