### ISSUE TITLE
Ra Group (file server)

### ISSUE THREAD

**Issue by FafnerKeyZee** [fastfire/deepdarkCTI#479]
Hello,

Dunno how to add it to Ransomgang :
hxxp://hkpomcx622gnqp2qhenv4ceyrhwvld3zwogr4mnkdeudq2txf55keoad.onion/  is a storage server used by Ra Group.

Best regards,

F_kZ_

**Comment by FafnerKeyZee** [comment]
What I mean is:
Files server ?
DLS?
Storage server?
Etc ;)

**Comment by frapava98** [comment]
Added as storage server.
