### ISSUE TITLE
How do I scrap the onion links to research or search using the links?

### ISSUE THREAD

**Issue by Blason** [fastfire/deepdarkCTI#569]
Hey Guys,

Wondering how do I scrap the links mentioned here so that I could ingest those in a database or so like elasticsearch and then searching is pretty easy? OR is there another way to search through the links provided? Can you please help?

TIA
Blason R

**Comment by soufianetahiri** [comment]
This project is actively maintained and it does exactly what you need 
https://github.com/joshhighet/ransomwatch

**Comment by Blason** [comment]
I mean not only for ransomware groups but wanted to search through darkweb
for my organisation details or email addresses or through irc forums.
Infact wanted to know how do I leverage these links and build a darkweb
search using elastic search maybe.
