### ISSUE TITLE
Does any one know AnonymousSudan current telegram channel

### ISSUE THREAD

**Issue by Blason** [fastfire/deepdarkCTI#583]
Hi Folks,

Not a issue though - But trying to look for AnonymousSudan Online Telegram channel. The one which is mentioned seems to be offline.

TIA

**Comment by ErezDasa** [comment]
https://t.me/xAnonymousSudan

**Comment by Blason** [comment]
Thanks buddy

**Comment by Blason** [comment]
Issue resolved with correct telegram link
