### ISSUE TITLE
Discord links not working

### ISSUE THREAD

**Issue by d7e7r7** [fastfire/deepdarkCTI#7]
I hope I'm not doing something wrong but I can't see anything on the Discord links? 

- https://discord.com/channels/828102975838748752/828194003103121439
- https://discord.com/channels/844252443214610492/844349064237809675

**Comment by fastfire** [comment]
Hi @d7e7r7 , I just fix with a temporary invite code.

**Comment by d7e7r7** [comment]
Thanks for the quick response.

**Comment by reynas** [comment]
Hi @fastfire, can you "refresh" the discord invites please?
Thanks for your work!

**Comment by fastfire** [comment]
> Hi @fastfire, can you "refresh" the discord invites please?
> Thanks for your work!

Done!
